---
title: "Leslie Matrix Practice"
author: "Vedika"
format: html
editor: visual
---

## Matrice Practice
Create a matrice and mess with it! 
```{r}
# make a sequence of values from 1 to 10
my_values <- seq(from = 1, to = 10,by =1)
# always double check by printing or running variable for output 
my_values

# convert to matrix
my_matrix <- matrix(data = my_values, nrow = 2, ncol = 5, byrow = T)

my_matrix

# matrix(data = my_values, nrow = 2, ncol = 3, byrow = T) # warning because dimensions do not provide enough slots for 10 numbers





```

```{r}
my_values_2 <- seq(from = 21, to = 30)
my_matrix2 <- matrix(data = my_values_2, nrow = 2, byrow = T)
my_matrix2

my_matrix - my_matrix2

```

## Matrix multiplication 
```{r}
cats <- matrix(data = c(0,4,3,1), nrow = 2, byrow=T)
dogs <- matrix (data = c(6, -3, 0, 2), nrow = 2, byrow = T)

cats 
dogs

cats %*% dogs

```

## Leslie matrix example
Create a projection matrix. This is the center matrix that describes how the pop size at time t is projected into t+1. 

```{r}
# create matrix 
insect_leslie <- matrix(c(0,0,600,0.2,0,0, 0,0.08), nrow = 3, ncol = 3, byrow = T)
 insect_leslie



```

```{r}
#insect lifestage population size (year 0 )
insect_y0 <- c(1200, 700, 500)
```

# Find the pop for each lifestage at year 1
```{r}
insect_yr1 <- insect_leslie%*% insect_y0

insect_yr1


```

Find the pop for each lifestage at year 2
```{r}
insect_yr2 <- insect_leslie%*% insect_yr1

insect_yr2

insect_yr3 <- insect_leslie%*% insect_yr2
insect_yr3

```

### another leslie matrix example






